//Header
export const OPENMENU = "OPENMENU";
export const CLOSEMENU = "CLOSEMENU";
export const OPENSIDEBAR = "OPENSIDEBAR";
export const CLOSESIDEBAR = "CLOSESIDEBAR";

//StateHome
export const GET_USERGROUP = "GET_USERGROUP";
export const GET_BUDGET_FUNDING = "GET_BUDGET_FUNDING";
export const GET_BUDGET_FUNDING_ACADEMIC = "GET_BUDGET_FUNDING_ACADEMIC";
export const GET_COUNT_FUNDING = "GET_COUNT_FUNDING";
export const GET_COUNT_FUNDING_ACADEMIC = "GET_COUNT_FUNDING_ACADEMIC";

// Funding
export const GET_COORDINATOR_FUNDING = "GET_COORDINATOR_FUNDING";
export const INSERT_COORDINATOR_FUNDING = "INSERT_COORDINATOR_FUNDING";
export const CLEAR_COORDINATOR_FUNDING = "CLEAR_COORDINATOR_FUNDING";
export const GET_COORDINATOR_FUNDING_ID = "GET_COORDINATOR_FUNDING_ID";
export const UPDATE_COORDINATOR_FUNDING = "UPDATE_COORDINATOR_FUNDING";
export const DELETE_COORDINATOR_FUNDING = "DELETE_COORDINATOR_FUNDING";

export const GET_SOURCEFUND = "GET_SOURCEFUND";
export const INSERT_SOURCEFUND = "INSERT_SOURCEFUND";
export const GET_PROJECT_TYPE = "GET_PROJECT_TYPE";
export const GET_YEAR = "GET_YEAR";
// export const UPDATE_INPUT = "UPDATE_INPUT";

// Funding_Academic
export const GET_COORDINATOR_FUNDING_ACADEMIC =
  "GET_COORDINATOR_FUNDING_ACADEMIC";
export const GET_COORDINATOR_FUNDING_ACADEMIC_ID =
  "GET_COORDINATOR_FUNDING_ACADEMIC_ID";
export const UPDATE_COORDINATOR_FUNDING_ACADEMIC =
  "UPDATE_COORDINATOR_FUNDING_ACADEMIC";
export const DELETE_COORDINATOR_FUNDING_ACADEMIC =
  "DELETE_COORDINATOR_FUNDING_ACADEMIC";

export const GET_RESEARCH_FACULTY = "GET_RESEARCH_FACULTY";
export const GET_BUDGET_TYPE = "GET_BUDGET_TYPE";
export const GET_FUNDING_STATUS = "GET_FUNDING_STATUS";

//ConceptProposal

export const GET_CONCEPT_PROPOSAL = "GET_CONCEPT_PROPOSAL";

// AddConceptProposal
export const ADD_CONCEPT = "ADD_CONCEPT";
export const ADD_SUB_CONCEPT = "ADD_SUB_CONCEPT";
export const ADD_STUDYAREA = "ADD_STUDYAREA";
export const ADD_NETWORK = "ADD_NETWORK";
// InsertConceptProposal
export const INSERT_CONCEPT = "INSERT_CONCEPT";
export const CLEAR_CONCEPT = "CLEAR_CONCEPT";

export const GET_USER = "GET_USER";
export const GET_CO_RESEARCH_GROUP = "GET_CO_RESEARCH_GROUP";

export const CREATE_TUTORIAL = "CREATE_TUTORIAL";
export const RETRIEVE_TUTORIALS = "RETRIEVE_TUTORIALS";
export const UPDATE_TUTORIAL = "UPDATE_TUTORIAL";
export const DELETE_TUTORIAL = "DELETE_TUTORIAL";
export const DELETE_ALL_TUTORIALS = "DELETE_ALL_TUTORIALS";
